version: '3.9'
 
services:
  codeleapapp:
    container_name: codeleapapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./codeleapapp:/codeleapapp
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:14-alpine
    env_file:
      - ./dotenv_files/.env